% Alin: Linearization of quadrotor continuous-time model dF/dx|_op.
%
% --
% Control for Robotics
% Assignment 2
%
% --
% Technical University of Munich
% Learning Systems and Robotics Lab
%
% Course Instructor:
% Angela Schoellig
% schoellig@utias.utoronto.ca
%
% Teaching Assistants: 
% SiQi Zhou: siqi.zhou@tum.de
% Lukas Brunke: lukas.brunke@tum.de
%
% This script is adapted from the course on Optimal & Learning Control for
% Autonomous Robots at the Swiss Federal Institute of Technology in Zurich
% (ETH Zurich). Course Instructor: Jonas Buchli. Course Webpage:
% http://www.adrlab.org/doku.php/adrl:education:lecture:fs2015
%
% --
% Revision history
% [14.05.25]    first version

function A = Alin(in1,in2,in3)
%ALIN
%    A = ALIN(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    25-May-2014 19:06:44

Fz = in2(1,:);
Mx = in2(2,:);
My = in2(3,:);
Thxxyy = in3(2,:);
Thzz = in3(3,:);
dqph = in1(10,:);
dqps = in1(12,:);
dqth = in1(11,:);
mQ = in3(1,:);
qph = in1(4,:);
qps = in1(6,:);
qth = in1(5,:);
t2 = 1.0./mQ;
t3 = cos(qth);
t4 = sin(qph);
t5 = cos(qph);
t6 = sin(qth);
t7 = 1.0./Thxxyy;
t8 = cos(qps);
t9 = sin(qps);
t10 = 1.0./t3;
t11 = Thxxyy.*2.0;
t12 = Thzz-t11;
t13 = qth.*2.0;
t14 = cos(t13);
t15 = My.*t9;
t16 = sin(t13);
t17 = 1.0./t3.^2;
t18 = qth.*3.0;
t19 = sin(t18);
t20 = My.*t8;
t21 = Mx.*t9;
t22 = t20+t21;
t23 = t3.^2;
t24 = t6.^2;
t25 = Thzz.*dqps.*t6;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-Fz.*t2.*t3.*t5,-Fz.*t2.*t3.*t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fz.*t2.*t3,Fz.*t2.*t4.*t6,-Fz.*t2.*t5.*t6,-t6.*t7.*t17.*(t15-Mx.*t8+Thzz.*dqps.*dqth-Thxxyy.*dqph.*dqth.*t6.*2.0+Thzz.*dqph.*dqth.*t6)-dqph.*dqth.*t7.*t12,-dqph.*t7.*(t25+Thxxyy.*dqph.*t14-Thzz.*dqph.*t14),t7.*t17.*(Mx.*t8.*-4.0+My.*t9.*4.0+Thzz.*dqps.*dqth.*4.0-Thxxyy.*dqph.*dqth.*t6.*9.0-Thxxyy.*dqph.*dqth.*t19+Thzz.*dqph.*dqth.*t6.*5.0+Thzz.*dqph.*dqth.*t19).*(1.0./4.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t7.*t10.*t22,-t7.*(t15-Mx.*t8),t6.*t7.*t10.*t22,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-dqth.*t6.*t7.*t10.*t12,t7.*(-Thxxyy.*dqph.*t16+Thzz.*dqps.*t3+Thzz.*dqph.*t16),dqth.*t7.*t10.*(Thzz-t11+Thxxyy.*t23-Thzz.*t23),0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-t7.*t10.*(Thzz.*dqps-Thxxyy.*dqph.*t6.*2.0+Thzz.*dqph.*t6),0.0,t7.*t10.*(t25-Thxxyy.*dqph-Thxxyy.*dqph.*t24+Thzz.*dqph.*t24),0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-Thzz.*dqth.*t7.*t10,Thzz.*dqph.*t3.*t7,Thzz.*dqth.*t6.*t7.*t10],[12, 12]);
