% main_system_id: Main script for Problem 3.2 (b)
%
% --
% Control for Robotics
% Assignment 3
%
% --
% Technical University of Munich
% Learning Systems and Robotics Lab
%
% Course Instructor:
% Angela Schoellig
% angela.schoellig@tum.de
%
% Teaching Assistants: 
% SiQi Zhou: siqi.zhou@tum.de
% Lukas Brunke: lukas.brunke@tum.de
%
% --
% Revision history
% [20.03.07, SZ]    first version
% [22.03.02, SZ]    second version

clear all
close all
clc

addpath(genpath(pwd));

%% General
% Result and plot directory
save_dir = './results/';
mkdir(save_dir);

%% Parameter estimation
data_size = [1, 10, 100, 1000];
theta_blr_est = [];
theta_cov_blr_est = [];
theta_lr_est = [];

for D = data_size
    % Generate ID data
    [id_data] = generate_param_iddata(D);
    
    % ================== [TODO] Parameter Estimation =================
    % Problem 3.2 (b): Write a 'param_id' function that computes the
    % parameter estimates based on the identification dataset 'id_data'.
    % The structure 'id_data' contains the input-output data generated by
    % the uncertain mountain car environment {state_cur, input_cur,
    % state_nxt}.
    [mu_lr, mu_blr, cov_blr] = param_id(id_data);
    
    % Record estimation results
    theta_lr_est = [theta_lr_est, mu_lr];
    theta_blr_est = [theta_blr_est, mu_blr];
    theta_cov_blr_est{size(theta_blr_est, 2)} = cov_blr;

    % % Plot estimates
    hdl = figure(1);
    hdl.Position(3) = 1155;
    plot_param_est(data_size, theta_lr_est, theta_blr_est, theta_cov_blr_est);

    % Print results
    fprintf('\nD = %d\n', D);
    fprintf('LR: %.4f, %.4f\n', mu_lr(1), mu_lr(2));
    std_blr = sqrt(diag(cov_blr));
    fprintf('BLR: %.4f, %.4f\n', mu_blr(1), mu_blr(2));
    fprintf('BLR Uncertainty: %.4f, %.4f\n', std_blr(1), std_blr(2));

    waitforbuttonpress;
end

% Save plot
saveas(gcf, strcat(save_dir, 'Parameter Estimation2.png'));